<%@ page import="javax.jdo.*"%>
<%@ page import="com.google.appengine.api.users.*"%>
<%@ page import="beans.*"%>
<%@ page import="utils.*"%>
<%@ page import="controller.*"%>
<%@ page import="java.text.*"%>
<%@ page import="java.util.*"%>
<%@ page import="java.util.logging.*"%>
<%@ page import="com.google.appengine.repackaged.org.json.*"%>
<%@ page import="com.google.appengine.api.datastore.Text"%>
<%
UserService userService = UserServiceFactory.getUserService();
User user = userService.getCurrentUser();

//check if it is and admin who is connected
if((user != null)&&(userService.isUserAdmin()==true)) 
{
	
PersistenceManager pm=null;
String accept_message="";
String accept_message_Title="";
try
{
   pm = PMF.get().getPersistenceManager();
   Query query=pm.newQuery(T_Config.class,"str_Name== str_NameP");
   query.declareParameters("String str_NameP");

    T_Config tConfig=null;
    //get the accept message
    List<T_Config> lstConfigs=(List<T_Config>)query.execute(Parameters.accept_message.name());
    if(!lstConfigs.isEmpty())
     {
       //if exist get value
	   accept_message=lstConfigs.get(0).getTextValue().getValue();
     }
   else
   {
	   
	   //if not exist, create it
	tConfig=new T_Config();
	tConfig.setLg_Key_ID(DateUtils.getTimeId());
	tConfig.setStr_Name(Parameters.accept_message.name());
	tConfig.setStrDescription("content sent when a CV is accepted");
	tConfig.setTextValue(new Text(EmailSender.ACCEPTED_CV));
	
	//make the accept message persistant
	pm.makePersistent(tConfig);
	System.out.print("save config");
  }
    
    
 query=pm.newQuery(T_Config.class,"str_Name== str_NameP");
 query.declareParameters("String str_NameP");

 tConfig=null;
 
 //get the accept message title 
 lstConfigs=(List<T_Config>)query.execute(Parameters.accept_message_Title.name());
    if(!lstConfigs.isEmpty())
        {
	     accept_message_Title=lstConfigs.get(0).getTextValue().getValue();
	     System.out.print("config "+accept_message_Title);
       }

   else
   {
	//if it does not exist,create it
	tConfig=new T_Config();
	tConfig.setLg_Key_ID(DateUtils.getTimeId());
	tConfig.setStr_Name(Parameters.accept_message_Title.name());
	tConfig.setStrDescription("title of content sent when a CV is accepted");
	tConfig.setTextValue(new Text("CV received and kept"));
	pm.makePersistent(tConfig);
	System.out.print("save config");
   }
}
catch(Exception ex)
{
	ex.printStackTrace();
}
finally
{
	pm.close();
}
%>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<script type="text/javascript" src="jquery/jquery-plus-jquery-ui.js"></script>
<link type="text/css" href="sample-style/ui-sui.css" rel="stylesheet" />
<link rel="stylesheet" href="tinyeditor/style.css" />
<link rel="stylesheet" href="common.css" type="text/css" />
<script type="text/javascript" src="tinyeditor/tinyeditor.js"></script>
<script type="text/javascript" src="common.js"></script>
<script type="text/javascript">
	/* ------ Code generated by IxEdit (ixedit.com). ------ */
	if(window.ixedit){ixedit.deployed = true};
	if(window.jQuery){jQuery(function(){
		




		
	    $('#tabAcceptMessages').ajaxStart( showWaiting); 

	    $('#tabAcceptMessages').ajaxStop( closeWaiting); 
	    
		})};



		
</script>
</head>
<body>
<div id="divConfirmDialog" class="invisible" style="text-align: center"></div>
<div id="popMessage" class="invisible"></div>
<div id="popNote" class="invisible"></div>
<div id="waiting_message" class="invisible"><img
	src="ajax-loader.gif" /></div>
<table border="0" id="tabAcceptMessages">
	<tr>
		<td>Title</td>
	</tr>
	<tr>
		<td style="text-align: left;" id="tdAcceptMessage"><input
			type="text" name="strAcceptTitle" id="strAcceptTitle"
			value="<%=accept_message_Title %>"></td>
	</tr>
	<tr>
		<td>Content</td>
	</tr>
	<tr>
		<td style="text-align: left;"><textarea name="strAcceptMessage"
			id="strAcceptMessage" cols="45" rows="5"><%=accept_message %></textarea></td>
	</tr>
	<tr>
		<td>
		<div align="center">
		<button onclick="saveValue();" class="uibutton">save</button>
		</div>
		</td>
	</tr>
</table>


<script type="text/javascript">
var txtAcceptMessage = new TINY.editor.edit('editor',{
	id:'strAcceptMessage',
	width:584,
	height:175,
	cssclass:'te',
	controlclass:'tecontrol',
	rowclass:'teheader',
	dividerclass:'tedivider',
	controls:['bold','italic','underline','strikethrough','|','subscript','superscript','|',
			  'orderedlist','unorderedlist','|','outdent','indent','|','leftalign',
			  'centeralign','rightalign','blockjustify','|','unformat','|','undo','redo','n',
			  'font','size','style','|','image','hr','link','unlink','|','cut','copy','paste','print'],
	footer:true,
	fonts:['Verdana','Arial','Georgia','Trebuchet MS'],
	xhtml:true,
	cssfile:'tinyeditor/style.css',
	bodyid:'editor',
	footerclass:'tefooter',
	toggle:{text:'source',activetext:'wysiwyg',cssclass:'toggle'},
	resize:{cssclass:'resize'}
});
/**
 * function to save the value of the accept message and title
 */
saveValue=function()
{
	txtAcceptMessage.post() ;
	var strAcceptTitle=document.getElementById("strAcceptTitle").value;
    var strAcceptMessage=document.getElementById("strAcceptMessage").value;
    var dataString = 'task=updateAcceptMessage&strAcceptTitle='
	+strAcceptTitle+'&strAcceptMessage='+strAcceptMessage;	
	
  		$.ajax({
		      type: "GET",
		      url: "requests.jsp",
		      data: dataString ,
		      success: function(msg)
		      {
		    
  			if(msg.indexOf("OK")>=0)
		      {
			      //alert("message saved");
			     showPopup(200,100,1000,"message saved");
			     // $("#flex1").flexReload();
			      closePopUp(1000);
		      }
		      else{
		    	 // alert("operation failed try again");
		    	 showPopup(200,100,1000,"operation failed try again");
		    	  closePopUp(1000);
		      }
			   }
		     });

};

</script>
</body>
</html>
<%}%>