<%@page import="com.google.appengine.api.datastore.Key"%>
<%@page import="java.util.ArrayList"%>
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ page import="java.util.List"%>
<%@ page import="javax.jdo.*"%>
<%@ page import="com.google.appengine.api.users.User"%>
<%@ page import="com.google.appengine.api.users.UserService"%>
<%@ page import="com.google.appengine.api.users.UserServiceFactory"%>
<%@ page import="beans.*"%>
<%@ page import="java.text.*"%>
<%@ page import="controller.*"%>
<%@ page import="utils.*"%>
<%@ page import="com.google.appengine.repackaged.org.json.*"%>
<%@ page import="java.util.logging.Logger"%>
<%

 /**
 MANAGE CV in grid
 **/
 
String strStatus=null;
List<T_Job_Category> lstJobCategories=JobCategController.getJobCategs(); // get all the job categs
T_Job_Category jobCategory=null;
String strJobCategoryName = "";
String lg_Job_Category_ID=null;

if(lstJobCategories==null) 
	{
	lstJobCategories=new ArrayList<T_Job_Category>();
	
	}

if(request.getParameter("strStatus")!=null)
	{
	session.setAttribute("strStatus",request.getParameter("strStatus"));
	}

if(request.getParameter("lg_Job_Category_ID")!=null)
{
session.setAttribute("lg_Job_Category_ID",request.getParameter("lg_Job_Category_ID"));
}

 strStatus=session.getAttribute("strStatus")==null?null:session.getAttribute("strStatus").toString();
 lg_Job_Category_ID=session.getAttribute("lg_Job_Category_ID")==null?null:session.getAttribute("lg_Job_Category_ID").toString();

 System.out.println("Statut en session= "+strStatus);
%>

<link type="text/css" href="sample-style/ui-sui.css" rel="stylesheet" />
<script type="text/javascript">
	/* ------ Code generated by IxEdit (ixedit.com). ------ */
	if(window.ixedit){ixedit.deployed = true};
	if(window.jQuery){jQuery(function(){
		(function(){ var target = jQuery('input#dateDeb'); target.datepicker({dateFormat:'mm/dd/yy',dayNamesMin:['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],dayNamesShort:['Sun', 'Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat'],monthNames:['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],monthNamesShort:['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],showOn:'button',showButtonPanel: true,currentText: 'This Month',closeText: 'Close'}); })();
		(function(){ var target = jQuery('input#dateFin'); target.datepicker({dateFormat:'mm/dd/yy',dayNamesMin:['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],dayNamesShort:['Sun', 'Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat'],monthNames:['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],monthNamesShort:['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],showOn:'button',showButtonPanel: true,currentText: 'This Month',closeText: 'Close'}); })();
	})};
</script>
<h1></h1>
<div id="searchbar">
<center>
<table width="100%" border="0" id="tabSearchBar">
	<tr>
		<td width="20%" style="text-align: left;">From</td>
		<td width="20%"><input type="text" name="dateDeb" id="dateDeb"
			value="" /></td>
		<td style="text-align: left;" width="10%">To</td>
		<td width="20%"><input type="text" name="dateFin" id="dateFin"
			value="" /></td>
		<td width="10%">Status</td>
		<td width="20"><select name="strStatus" id="strStatus">
			<option value="ALL" <%="ALL".equals(strStatus)?"selected":"" %>>ALL</option>
			<option value="unsorted"
				<%="unsorted".equals(strStatus)?"selected":"" %>>Unsorted</option>
			<option value="accepted"
				<%="accepted".equals(strStatus)?"selected":"" %>>Accepted</option>
			<option value="rejected"
				<%="rejected".equals(strStatus)?"selected":"" %>>Rejected</option>
		</select></td>
	</tr>
	<tr>
		<td style="text-align: left;" width="20%">Job Category</td>
		<td width="20%"><select name="lg_Job_Category_ID"
			id="lg_Job_Category_IDs">
			<option value=""></option>
			<%for(T_Job_Category job:lstJobCategories) 
    {%>
			<option
				<%=job.getLg_Job_Category_ID().equals(lg_Job_Category_ID)?"selected":"" %>
				value="<%=job.getLg_Job_Category_ID() %>"><%=job.getStrJobCategoryName()%></option>
			<%} %>
		</select></td>
		<td width="10%">Email</td>
		<td width="20%"><input type="text" name="strUserEmail"
			id="strUserEmails" value="" onchange="echeck(this.value)" /><b
			id="lblValid"></b></td>
		<td width="20" colspan="2" style="text-align: center;">
		<button class='uibutton' onclick="searchClick()" >search</button>
		</td>
	</tr>
</table>
</center>
</div>
<div id="message"></div>

<center>

<div id="forms"></div>

<table id="flex1" style="display: none"></table>
</center>
<input type="hidden" id="lg_CV_ID" value=""/>

<input type="hidden" id="lg_Task" value=""/>
<input type="hidden" id="str_Message" value=""/>
<style>
.flexigrid div.fbutton .add {
	background: url(css/images/add.png) no-repeat center left;
}

.flexigrid div.fbutton .delete {
	background: url(css/images/close.png) no-repeat center left;
}

.flexigrid div.fbutton .accept {
	background: url(css/images/yes.png) no-repeat center left;
}

.flexigrid div.fbutton .reject {
	background: url(css/images/no.png) no-repeat center left;
}

.flexigrid div.fbutton .view {
	background: url(css/images/ico-docs.png) no-repeat center left;
}

.flexigrid div.fbutton .feedback {
	background: url(css/images/info.png) no-repeat center left;
}
</style>
<script type="text/javascript">

/**
 * function called after showing confirm dialog 
 */
ajaxOperation=function()
{

	var target = jQuery('div#divConfirmDialog');
	target.dialog('close');
	var lg_CV_ID=document.getElementById("lg_CV_ID").value;//get the CV id
	var lg_Task=document.getElementById("lg_Task").value;// get the task : rejectCV, acceptCV,deleteCV
	
	var dataString = 'task='+lg_Task+'&lg_CV_ID='+lg_CV_ID; // the final request
	//alert(dataString);

	//ajax to to the operation
	$.ajax({
		      type: "POST",
		      url: "requests.jsp",
		      data: dataString,
		      success: function(msg)
		      {

                // if the operation succeeds requests.jsp should return ok
				if(msg.indexOf("OK")>=0)
					      {

					       var str_Message=document.getElementById("str_Message").value;//read the success message
					       showPopup(200,150,1000,str_Message);// show the success message
						   $("#flex1").flexReload(); //reload the Grid
						      closePopUp(1000);
					      }
					      else{
					    	  showPopup(200,100,1000,"CV operation Failed");
					    	 // alert("CV operation Failed");
					      }
				 
			   }
		     });
}

//delete cv on grid
deleteCVGrid = function()
{
	 document.getElementById("lg_Task").value="deleteCV";
	 document.getElementById("str_Message").value="CV deleted";
		
      showConfirm("delete this CV?",ajaxOperation);// comments in common.js
	

 };  

 //accept cv in grid  
 acceptCVGrid = function()
 {
	document.getElementById("lg_Task").value="acceptCV";
 	document.getElementById("str_Message").value="CV accepted , an email has been sent to the user";

    showConfirm("confirm accept this CV?",ajaxOperation);
 	
};    

//reject cv in grid
rejectCVGrid = function()
  {
		
    	document.getElementById("lg_Task").value="rejectCV";
    	document.getElementById("str_Message").value="CV rejected , an email has been sent to the user";
    	 
        showConfirm("confirm reject this CV?",ajaxOperation);
  	

 };    

 //load data on grid 	 	
 function loadData()
 {

			$('.flexme1').flexigrid();
			$('.flexme2').flexigrid({height:'auto',striped:false});

			$("#flex1").flexigrid
			(
			{
			url: 'cvs.jsp', //url to load json formatted cv
			dataType: 'json',
			colModel : [
			    {display: 'User Email', name : 'strUserEmail', width : 150, sortable : false, align: 'left'},
				  {display: 'First name', name : 'strFirstName', width : 125, sortable : false, align: 'left'},
				  {display: 'Last name', name : 'strLastName', width : 100, sortable : false, align: 'left'},					
                 {display: 'File Name', name : 'strFileName', width :150, sortable :false, align: 'left'},
				{display: 'File Size', name : 'lgFileSize', width : 50, sortable : false, align: 'left'},
	            {display: 'Received Date', name : 'dtReceivedDate', width : 100, sortable : true, align: 'left'}
				
						],
			buttons : [
		
				{name: 'View CV', bclass: 'view', onpress : test},
				{separator: true},
				{name: 'Note', bclass: 'feedback', onpress : test},
				{separator: true},
				<% if(T_CV.STATUS_NON_SORTED.equals(strStatus))
				{
				%>
				{name: 'Accept', bclass: 'accept', onpress : test},
				{separator: true},
				{name: 'Reject', bclass: 'reject', onpress : test},
				{separator: true},
				<%}%>
				{name: 'download CV', bclass: 'view', onpress : test},
				{separator: true},
				{name: 'Delete', bclass: 'delete', onpress : test},
				{separator: true}
				
				],
			searchitems : [
{display: 'File Name', name : 'strFileName'},

				{display: 'First name', name : 'strFirstName'},
				{display: 'Last name', name : 'strLastName'},
				{display: 'User Email', name : 'strUserEmail', isdefault: true}
				],
			sortname: "dtReceivedDate",
			sortorder: "desc",
			usepager: true,
			title: 'Received CVs',
			useRp: false,
			rp: 10,
			showTableToggleBtn: false,
			width: 750,
			height: 230
			}
			);
 }

 //function called when a button on grid is clicked
function test(com,grid)
{
                // click on accept CV
	            if (com=='Accept')
				{ 	
				   var str= $('.trSelected',grid)[0].id;
		    	   var dataString = str.substring(3,str.length);

		    	     document.getElementById("lg_CV_ID").value=dataString; //set the ID hidden value
                     acceptCVGrid();
				}

				//click on reject CV
				else if (com=='Reject')
				{ 	
				   var str= $('.trSelected',grid)[0].id;
				   var dataString = str.substring(3,str.length);
                   document.getElementById("lg_CV_ID").value=dataString;
			       rejectCVGrid();
				}	
				//click on delete CV	
				else if (com=='Delete')
				{ 	
				   var str= $('.trSelected',grid)[0].id;
				   var dataString = str.substring(3,str.length);
                   document.getElementById("lg_CV_ID").value=dataString;
			       deleteCVGrid();
				}	

				//view cv in viewer
				else if (com=='View CV')
				{ 	
					var str= $('.trSelected',grid)[0].id;
			    	var dataString = 'lg_CV_ID='+str.substring(3,str.length);
			    	window.open("/viewer.jsp?"+dataString);													
				}	

				//download CV in some browser and OS the pdf file will be displayed
				else if (com=='download CV')
				{ 	
					var str= $('.trSelected',grid)[0].id;
			    	var dataString = 'task=viewCV&lg_CV_ID='+str.substring(3,str.length);
			    	window.open("/download?"+dataString);													
					}	
				else if (com=='Note')
				{ 	
					var str= $('.trSelected',grid)[0].id;
			    	var dataString = 'lg_CV_ID='+str.substring(3,str.length);

			    	popCVNote(str.substring(3,str.length));

			    														
					}				
			}

			

		$('b.top').click
		(
			function ()
				{
					$(this).parent().toggleClass('fh');
				}
		);


		
 
 loadData();
</script>
<script type="text/javascript">


//function called when click on search button
searchClick=function()
{
	var dateDeb=document.getElementById("dateDeb").value;//get the starting date
	var dateFin=document.getElementById("dateFin").value;//get the end date, so the search will be done on CV that dt_received>=dateDeb and dt_received<=dateFin
	var strStatus=document.getElementById("strStatus").value;//get the status if the search is done on cv of a specific category
	var lg_Job_Category_ID=document.getElementById("lg_Job_Category_IDs").value;
	{
	
	//alert(str);
	var dataString = 'task=setSearch&dateDeb='
    	+dateDeb+'&dateFin='+dateFin+"&strStatus="+strStatus+"&lg_Job_Category_ID="+lg_Job_Category_ID;   	
	//alert(dataString);		   

 $.ajax({
  type: "GET",
  url: "requests.jsp",
  data: dataString,
  success: function(msg){
	  $('#main').html(msg);
				
   }
 });
}
};
</script>

