<%@page import="com.google.appengine.api.datastore.Key"%>
<%@page import="java.util.ArrayList"%>
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ page import="java.util.*"%>
<%@ page import="javax.jdo.*"%>
<%@ page import="com.google.appengine.api.users.User"%>
<%@ page import="com.google.appengine.api.users.UserService"%>
<%@ page import="com.google.appengine.api.users.UserServiceFactory"%>
<%@ page import="beans.*"%>
<%@ page import="java.text.*"%>
<%@ page import="controller.*"%>
<%@ page import="utils.*"%>
<%@ page import="com.google.appengine.repackaged.org.json.*"%>
<%@ page import="java.util.logging.Logger"%>
<%
	UserService userService = UserServiceFactory.getUserService();
	User user = userService.getCurrentUser();
	String current=request.getParameter("lg_CV_ID");
	String currentIndex=request.getParameter("lg_CV_ID_pos");
	String strStatus=session.getAttribute("strStatus")==null?null:session.getAttribute("strStatus").toString();
	String lg_Job_Category_ID=session.getAttribute("lg_Job_Category_ID")==null?null:session.getAttribute("lg_Job_Category_ID").toString();
	PersistenceManager pm=null;
	pm = PMF.get().getPersistenceManager();
	Query query =null;
	query=pm.newQuery(T_CV.class,"lg_CV_ID==lg_CV_IDP");
	query.declareParameters("String lg_CV_IDP");
	List<T_Job_Category> lstJobCategories=JobCategController.getJobCategs();
	T_Job_Category jobCategory=null;
	String strJobCategoryName = "";
	if(lstJobCategories==null) 
		{
		lstJobCategories=new ArrayList<T_Job_Category>();
		
		}
	List<T_CV> lsTCV = (List<T_CV>)query.execute(current);
	T_CV oTCV=null;
	if(lsTCV!=null && !lsTCV.isEmpty())
	{
		strStatus=lsTCV.get(0).getStrStatus();
		lg_Job_Category_ID=lsTCV.get(0).getLg_Job_Category_ID();
		System.out.println(" JOB ID = "+lg_Job_Category_ID);
		jobCategory=JobCategController.getJobCategsByID(lg_Job_Category_ID);
		strJobCategoryName=jobCategory==null?"":jobCategory.getStrJobCategoryName();
		
		oTCV=lsTCV.get(0);
	
    
	
	if (user != null) 
	{
		List<String> lstT_CV=(List<String>)session.getAttribute("lstT_CV");
		String oCv=null;
		String oCvNext=null;
		String oCvPrevious=null;
		String oCvFirst=null;
		String oCvLast=null;
		int lg_Next=0;
		int lg_Previous=0;

		if(lstT_CV != null)
		{
			
			int intNum=Integer.parseInt(request.getParameter("lg_CV_ID_pos"));
			oCvFirst=lstT_CV.get(0);
			oCvLast=lstT_CV.get(lstT_CV.size()-1);
			lg_Next=intNum+1;
			lg_Previous=intNum-1;
			if(intNum==0) 
			{
				lg_Previous=lstT_CV.size()-1;
			}
			else if(intNum==(lstT_CV.size()-1))
			{
				lg_Next=0;
			}
			if(lstT_CV.size()==1)
			{
				lg_Next=0;
				lg_Previous=0;
			}
			oCv=lstT_CV.get(intNum);
			oCvNext=lstT_CV.get(lg_Next);
			oCvPrevious=lstT_CV.get(lg_Previous);
		%>

<link type="text/css" href="sample-style/ui-sui.css" rel="stylesheet" />
<script type="text/javascript">
	/* ------ Code generated by IxEdit (ixedit.com). ------ */
	if(window.ixedit){ixedit.deployed = true};
	if(window.jQuery){jQuery(function(){
		(function(){ var target = jQuery('input#dateDeb'); target.datepicker({dateFormat:'mm/dd/yy',dayNamesMin:['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],dayNamesShort:['Sun', 'Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat'],monthNames:['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],monthNamesShort:['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],showOn:'button',showButtonPanel: true,currentText: 'This Month',closeText: 'Close'}); })();
		(function(){ var target = jQuery('input#dateFin'); target.datepicker({dateFormat:'mm/dd/yy',dayNamesMin:['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],dayNamesShort:['Sun', 'Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat'],monthNames:['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],monthNamesShort:['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],showOn:'button',showButtonPanel: true,currentText: 'This Month',closeText: 'Close'}); })();

	    $('#main').ajaxStart(  function(event, ui) 
	    	    {
	    	$('#waiting_message').removeClass("invisible");
			var target = jQuery('div#waiting_message');
			target.show();
			if (!target.dialog('isOpen')) {
				target.dialog( {
					autoOpen :false,
					bgiframe :true,
					modal :true,
					resizable :false,
					width :200,
					height :200,
					position : [ 'center', 'center' ],
					draggable :true
				})
			}
			;
			target.dialog('open');
		}); 

	    $('#main').ajaxStop(  function(event, ui) 
	    	    {
	    	var target = jQuery('div#waiting_message');
	    	target.dialog('close');
			
	    	    }); 
		})};
</script>
<div id="searchbar">
<center>
<h1></h1>
<table width="100%" border="0" id="tabSearchBar">
	<tr>
		<td width="20%" style="text-align: left;">From</td>
		<td width="20%"><input type="text" name="dateDeb" id="dateDeb"
			value="" /></td>
		<td style="text-align: left;" width="10%">To</td>
		<td width="20%"><input type="text" name="dateFin" id="dateFin"
			value="" /></td>
		<td width="10%">Status</td>
		<td width="20"><select name="strStatus" id="strStatus">
			<option value="ALL" <%="ALL".equals(strStatus)?"selected":"" %>>ALL</option>
			<option value="unsorted"
				<%="unsorted".equals(strStatus)?"selected":"" %>>Unsorted</option>
			<option value="accepted"
				<%="accepted".equals(strStatus)?"selected":"" %>>Accepted</option>
			<option value="rejected"
				<%="rejected".equals(strStatus)?"selected":"" %>>Rejected</option>
		</select></td>
	</tr>
	<tr>
		<td style="text-align: left;" width="20%">Job Category</td>
		<td width="20%"><select name="lg_Job_Category_ID"
			id="lg_Job_Category_IDs">
			<option value="">ALL</option>
			<%for(T_Job_Category job:lstJobCategories) 
    {%>
			<option
				<%=job.getLg_Job_Category_ID().equals(lg_Job_Category_ID)?"selected":"" %>
				value="<%=job.getLg_Job_Category_ID() %>"><%=job.getStrJobCategoryName()%></option>
			<%} %>
		</select></td>
		<td width="10%">Email</td>
		<td width="20%"><input type="text" name="strUserEmail"
			id="strUserEmails" value="" onchange="echeck(this.value)" /><b
			id="lblValid"></b></td>
		<td width="20" colspan="2" style="text-align: center;">
		<button class='uibutton' onclick="searchViewerClick()" >search</button>
		</td>
	</tr>
</table>
</center>
</div>
<center><br>
<table width="100%" border="0" id="tabViewCV">
	<tr>
		<td colspan="6" width="100%">
		<table width="100%">
			<tr>
				<td style="text-align: left;" width="34%"><b>Email :</b><%=oTCV.getStrUserEmail()%></td>
				<td style="text-align: left;" width="33%"><b>Applicant :</b> <%=oTCV.getStrFirstName()+" "+oTCV.getStrLastName() %>
				</td>



				<td style="text-align: left;" width="33%"><b>Job Category :</b>
				<%=strJobCategoryName %></td>
				</td>
			</tr>
		</table>

		</td>

	</tr>
	<tr>
		<td width="10%" style="text-align: left;">
       <%if(lstT_CV.size()>1 && intNum!=0) {%>
          <button onclick="<%="viewCV("+"'"+oCvFirst+"','"+0+"')"%>" class="uibutton">
&lt;&lt;First
</button>
<%} %>
</td>

		<td width="25%" style="text-align: right;"><%if(lstT_CV.size()>1) {%>
          <button onclick="<%="viewCV("+"'"+oCvPrevious+"','"+lg_Previous+"')"%>" class="uibutton">
&lt;Previous
</button><%} %></td>
		<td width="25%" style="text-align: left;"></td>
		<td colspan="2" width="40%" style="text-align: left;">
<%if(lstT_CV.size()>1) {%>
          <button onclick="<%="viewCV("+"'"+oCvNext+"','"+lg_Next+"')"%>" class="uibutton">
 &gt;Next
</button>
<%} %>
</td>
		<td width="10%" style="text-align: right">

<%if(lstT_CV.size()>1 && intNum!=(lstT_CV.size()-1)) {%>
          <button onclick="<%="viewCV("+"'"+oCvLast+"','"+(lstT_CV.size()-1)+"')"%>" class="uibutton">
 &gt;&gt;Last
</button>
<%} %>

</td>
	</tr>

	<tr>
		<td width="18%" style="text-align: center;">
		<button class="uibutton" onclick="downloadCV('<%=oCv%>');">download</button>
		</td>
		<td width="16%" style="text-align: center;">
		<button class="cbutton" onclick="popCVNote('<%=oCv%>');"><img
			alt="OTE" src="images/note.gif"
			onmouseover="this.src='images/note_hover.gif';"
			onmouseout="this.src='images/note.gif'" /></button>
		</td>
		<td width="16%" style="text-align: center;">
		<%if(T_CV.STATUS_NON_SORTED.equals(strStatus)) { %>
		<button class="cbutton" onclick="acceptCVViewer();">
		<img alt="ACCEPT" src="images/accept.gif"
			onmouseover="this.src='images/accept_hover.gif';"
			onmouseout="this.src='images/accept.gif'" /></button>
		<%} %>
		</td>
		<td width="16%" style="text-align: center;">
		<%if(T_CV.STATUS_NON_SORTED.equals(strStatus)) { %>
		<button class="cbutton" onclick="rejectCVViewer();">
		<img alt="REJECT" src="images/reject.gif;"
			onmouseover="this.src='images/reject_hover.gif';"
			onmouseout="this.src='images/reject.gif';" /></button>

		<%} %>
		</td>
		<td width="16%" style="text-align: center">
		<button class="cbutton" onclick="deleteCVViewer();">
		<img alt="delete" src="images/delete.gif"
			onmouseover="this.src='images/delete_hover.gif';"
			onmouseout="this.src='images/delete.gif'" /></button>
		</td>

		<td width="18%"
			style="text-align: right; font-size: 18px; font-weight: bold"><%=(intNum+1)+"/"+lstT_CV.size() %></td>
	</tr>
</table>
</center>
<input type="hidden" id="lg_CV_ID" value="<%=current%>"/>
<input type="hidden" id="lg_CV_ID_pos" value="<%=intNum%>"/>
<input type="hidden" id="lg_Task" value=""/>
<input type="hidden" id="str_Message" value=""/>
<script type="text/javascript">

searchViewerClick=function()
{
	var dateDeb=document.getElementById("dateDeb").value;
	var dateFin=document.getElementById("dateFin").value;
	var strStatus=document.getElementById("strStatus").value;
	var strUserEmail=document.getElementById("strUserEmails").value;
	var lg_Job_Category_ID=document.getElementById("lg_Job_Category_IDs").value;
	{
	
	//alert(str);
	var dataString = 'task=viewerSearch&dateDeb='
    	+dateDeb+'&dateFin='+dateFin+"&strStatus="+strStatus+"&strUserEmail="+strUserEmail+"&lg_Job_Category_ID="+lg_Job_Category_ID;   	
	//alert(dataString);		   

 $.ajax({
  type: "GET",
  url: "requests.jsp",
  data: dataString,
  success: function(msg){
	//alert(msg);
	 //$("#flex1").flexReload();
	  $('#main').html(msg);
				
   }
 });
}
};




ajaxViewerOpereation=function()
{

	
    var target = jQuery('div#divConfirmDialog');
	target.dialog('close');

	var lg_Task=document.getElementById("lg_Task").value;
	var lg_CV_ID=document.getElementById("lg_CV_ID").value;
	var lg_CV_ID_pos=document.getElementById("lg_CV_ID_pos").value;
	
	
	var dataString = 'task='+lg_Task+'&lg_CV_ID='+lg_CV_ID+'&lg_CV_ID_pos='+lg_CV_ID_pos;
	
	$.ajax({
		      type: "POST",
		      url: "requests.jsp",
		      data: dataString,
		      success: function(msg)
		      {
				//alert("CV deleted");
				 var str_Message=document.getElementById("str_Message").value;
					  
				 showPopup(300,150,1000,str_Message);
			
				 $('#main').html(msg);

				 closePopUp(1000);
			   }
		     });
}


deleteCVViewer = function()
{
	 document.getElementById("lg_Task").value="deleteCVList";
	 	document.getElementById("str_Message").value="CV deleted";
		
showConfirm("delete this CV?",ajaxViewerOpereation);

	

 };    


 acceptCVViewer = function()
 {
 	
	 document.getElementById("lg_Task").value="acceptCVList";
	 	document.getElementById("str_Message").value="CV accepted , an email has been sent to the user";

	 showConfirm("confirm accept this CV?",ajaxViewerOpereation);
 	

  };    


  
  rejectCVViewer = function()
  {
  	
		document.getElementById("lg_Task").value="rejectCVList";
	 	document.getElementById("str_Message").value="CV rejected , an email has been sent to the user";
	 	 
	showConfirm("confirm reject this CV?",ajaxViewerOpereation);
  	

   };    	 		 	      
		</script>
<iframe
	src="http://docs.google.com/viewer?url=http%3A%2F%2Flimbelabstalent.appspot.com%2Fdownload%3Ftask%3DviewCV%26lg_CV_ID%3D<%=current%>&embedded=true"
	width="100%" height="780" style="border: none;"></iframe>
<%
	}
		else
		{
			%>

<h1>NO CV to Display</h1>
<%
		}
	}
		
	else {
		response.sendRedirect(userService.createLoginURL(request
				.getRequestURI()));
	}
	} 
	else
	{
		%>

<h1>NO CV to Display</h1>
<%
	}
%>